all:
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe" -Wall -pedantic -O3 -o bin2c D:\Documents_SPACE\GitHub\Repos\picow-iot-device\tools\bin2c.c
